services:
  db:
    image: postgres:15-alpine
    container_name: forum-api-db
    environment:
      POSTGRES_USER: forum_user
      POSTGRES_PASSWORD: forum_password
      POSTGRES_DB: forum_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: forum-api-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://forum_user:forum_password@db:5432/forum_db?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
